[target]
main = "src/main.crl"

[ffi]
enabled = false
export = [  ]
path = "src/core.c"

[extensors]
# You can add extensors from an external git repository!
repositories = [ "git@github.com:Carla-Corp/extensors.git" ]
